# Generated by Django 3.0.5 on 2020-04-03 18:55

from django.db import migrations, models
import viciapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('viciapp', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=viciapp.models.upload_image_dir_path),
        ),
    ]
