# Generated by Django 3.0.5 on 2020-04-05 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viciapp', '0002_auto_20200404_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='adress',
        ),
        migrations.AlterField(
            model_name='company',
            name='help_message',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='AdressPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='viciapp.Company')),
            ],
        ),
    ]
