# Generated by Django 3.0.5 on 2020-04-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viciapp', '0003_auto_20200405_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
