# Generated by Django 3.0.5 on 2020-04-05 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viciapp', '0004_auto_20200405_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='logo',
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adresspart',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adress_parts', to='viciapp.Company'),
        ),
    ]
