# Generated by Django 3.0.5 on 2020-04-06 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viciapp', '0006_auto_20200406_1137'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdressPart',
        ),
    ]
